### ISSUE TITLE
Add Kerberos authentication support

### ISSUE THREAD

**Issue by dcl** [python-zk/kazoo#130]
As of version 3.4, Zookeeper allows authentication via Kerberos, but at the moment only the Java client supports it. Are there plans to add this to Kazoo in the near future?

**Comment by romainr** [comment]
@mkomitee, do you have your current patches pushed somewhere? 

We are going to have a look (we use PyKerberos, not PyGSSAPI) to see how long it would take.

**Comment by mkomitee** [comment]
I'll see if I can dig them up.

**Comment by romainr** [comment]
Thanks, right now we went up with SASL module in https://github.com/python-zk/kazoo/pull/284

**Comment by mkomitee** [comment]
I submit #287 to serve as a reference. I hope it helps.

**Comment by bbangert** [comment]
I'd be happy to merge a new PR for this, until there's more traction on this I'm closing this issue.
