### ISSUE TITLE
Feature: Enable uncleaned exit

### ISSUE THREAD

**Issue by nailor** [python-zk/kazoo#147]
Currently, when a process running kazoo exists, due to an unhandled exception for example, kazoo tries to do a clean exit.

The clean exit happens because both handlers, gevent and threaded one, register their respective `stop` functions to `atexit`. In both cases the handler joins all still-running worker threads.

Now if one of these worker threads has been doing something that just blocks indefinitely (say, read a socket that no-one ever writes to), the process will just hang upon exit.

I'm proposing that we should have on option to pass either a timeout to the `disconnect`/`close` method that would then be passed to the thread joins or a flag that skips the joining altogether.

How does these sound? I'm more than happy to cook a patch for these

**Comment by irachex** [comment]
@nailor How do you work around?

**Comment by nailor** [comment]
@irachex We just made sure we don't block the kazoo, so fired callbacks and others in separate threads returning execution back to kazoo almost immediately
