### ISSUE TITLE
ChildrenWatch should notify the function when the node is deleted

### ISSUE THREAD

**Issue by jimfulton** [python-zk/kazoo#153]
The documentation doesn't go into any depth on the semantics of high-level data and children watches, so it's hard to know what the actual API is and what to report as a bug.

If you set a DataWatch on a node, the watch survives node deletion. When a node is deleted, None is passed to the handler.  The handler stays around and if the node is recreated, the handler is called with the new data.  I guess DataWatches also serve as
high-level existence watches. This is rather useful. Is it intentional? :)

In the case of ChildrenWatches, if a node is deleted, Kazoo logs an error, but doesn't call a handler.  Is this intentional?

**Comment by salmanfairoze** [comment]
@zk.ChildrenWatch("/producer")
def watch_children(children):
    print("Children are now: %s" % children)

I am using this function is a program where nodes are created like this ("/producer/node_1") and ("/producer/node_2") etc. But when I try to delete a node which is a child of /producer no event is triggered. There is no response from the watch function. I tried declaring the watch decorator before and after node creation but still no response. Anyhow there is just 1 response from the watch function which is by default during the creation of nodes. Any help please. By the way I am trying to create high availability on several slaves and keeping watch using the zookeeper. So if a slave fails I need to get it back with the help of zookeeper and at the same time do nothing when I am deleting slaves while I scale in. Any help is appreciated. By the way I am running all these components in docker container
