### ISSUE TITLE
Is there a way to release lock acquired by LockingQueue?

### ISSUE THREAD

**Issue by spankme** [python-zk/kazoo#159]
In following scenario:
1. A message comes into the /queue
2. It is being received by using .get() method on the queue object, msg = queue.get()
3. A process is starting based on the data in the msg, but it fails
4. The failure is detected, the cleanup proces starts and finishes properly

Is there a way to release the lock on the message so that it wont have to be deleted using queue.consume(), and would be available for another /queue listener for processing and consumption (or even the same process again, starting from scratch)? 

From my observations it seems the lock remains there indefinitely, until the process is connected to the queue.

**Comment by bsanders** [comment]
Just dropping a friendly reminder here to say the above pull request fixes this issue and includes a unit test.

**Comment by harlowja** [comment]
:+1:  seems ok to me!

**Comment by bbangert** [comment]
I'd like to include this fix @bsanders, the PR was well done, I think after a rebase it should apply cleanly. Tests run more consistently as well which should help with merging. Thanks again for looking into this!

**Comment by bsanders** [comment]
Thanks @bbangert, but you just accepted a separate PR's that covered the code portion, and someone else merged in a unit test, so feature-wise this issue is covered.

However, I did find a bug in the code you pulled in that wasn't in mine.  There's a missing set of parens on a function call, see PR #449.

**Comment by bbangert** [comment]
Oops, sorry about that! I take it this issue can be considered closed then with your fix and the other PR that was merged?

**Comment by StephenSorriaux** [comment]
I close this issue since #302 added the feature. Thanks.
