### ISSUE TITLE
kazoo patch to workaround select's file descriptor limitation

### ISSUE THREAD

**Issue by pattyshack** [python-zk/kazoo#171]
I wrote a patch to deal with the fact that select cannot handle file descriptors larger than 1024 (This problem is common to most posix select implementations).  I would like to upstream this change.

This patch is only applicable to posix based systems (Windows does not support epoll).  

patch: https://www.dropbox.com/s/9dae2bfk1jfilwr/kazoo-1.3.1.patch

original thread: https://groups.google.com/forum/#!topic/python-zk/kzX_8BBBpCM

**Comment by bbangert** [comment]
If this can be done as a PR and merged cleanly I'd be happy to include it. Closing this otherwise, feel free to re-open along with a PR using the latest master if you'd like to address it.
