### ISSUE TITLE
Memory leak in LockingQueue

### ISSUE THREAD

**Issue by mdevaev** [python-zk/kazoo#175]
Frequent calls of LockingQueue.get(timeout) lead to memory leaks, if data in the queue rarely appear. This is due to the fact that more and more instances of `check_for_updates()` registered as watchers.
In our case, this led to a huge memory consumption (several gigabytes per day).
Simple test to reproduce the problem:

```
import resource

client = KazooClient("localhost")
client.start()
lq = client.LockingQueue("/leak-test")
getrss = lambda: resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

before = getrss()
print("Processing...")
for _ in range(10000):
    lq.get(0.001)
print("RSS: +%d\n[Enter] to exit" % (getrss() - before))
input()
```

Output:

```
Processing...
RSS: +16976
[Enter] to exit
```

**Comment by abdarraafi** [comment]
Was this bug fixed?

I don't see a commit related to it in this thread other than a note in the source that links here, but the bug is closed.

**Comment by radix** [comment]
yeah, it seems a bit weird that this ticket is marked closed just because the bug is documented.
