### ISSUE TITLE
Hang forever after connection established (LANG env issue)

### ISSUE THREAD

**Issue by douyuan** [python-zk/kazoo#187]
# Summary

Hang forever after connection established when:
1. LANG is not en_US.UTF-8;
2. use chroot;
3. import from another file;
# Environment

Red Hat Enterprise Linux Server release 5.7 (Tikanga)
Linux tc_69_200 2.6.18-274.el5xen #1 SMP Fri Jul 8 17:45:44 EDT 2011  x86_64 x86_64 GNU/Linux
python 2.7.1
zookeeper-3.4.3
kazoo-1.3.1 (git master branch also works)
# Steps to Reproduce
1. create outer.py & inner.py (see below);
2. start zookeeper on localhost;
3. create path /open_acl_unsafe in zookeeper;
4. run "LANG=C python outer.py 1";
# Expected Results

before zk.start, root=[/open_acl_unsafe]
after zk.start
# Actual Results

before zk.start, root=[/open_acl_unsafe]
**PROGRAM HANG FOREVER**
# The following commands run successfully

LANG=C           python outer.py
LANG=en_US.UTF-8 python outer.py 1
LANG=en_US.UTF-8 python outer.py
LANG=C           python inner.py 1
LANG=C           python inner.py
LANG=en_US.UTF-8 python inner.py 1
LANG=en_US.UTF-8 python inner.py

Eager to know if you can reproduce this problem.
# Used files
## outer.py

``` python
from inner import *
```
## inner.py

``` python
import sys, logging
#logging.basicConfig(level=logging.DEBUG)
import kazoo.client

TIMEOUT = 10.0
HOSTS = '127.0.0.1:2181'
root = '/open_acl_unsafe' if len(sys.argv) > 1 else ''

zk = kazoo.client.KazooClient(hosts=HOSTS + root, timeout=TIMEOUT)
print 'before zk.start, root=[%s]' % root
zk.start(timeout=TIMEOUT)
print 'after zk.start'
```

**Comment by agussman** [comment]
Quick note for others who may encounter this issue:

It's possible for LANG to be set to en_US.UTF-8 but you still encounter the issue because you have LC_ALL=C elsewhere in the environment. Changing both LANG and LC_ALL to en_US.UTF-8 will prevent the issue.

**Comment by bbangert** [comment]
Ok, closing this issue as it should remain visible to google searches about it and the workaround above remedies it.
