### ISSUE TITLE
Unable to handle select.error for EINTR in connection loop

### ISSUE THREAD

**Issue by mkomitee** [python-zk/kazoo#188]
When my process receives a signal (e.g. `TERM` or `INT`) I'd like to do some immediate cleanup with zookeeper. 

My main thread handles it fine and attempts to use its `KazooClient` to `leave` a `ShallowParty`, but doing so appears to block forever.

Looking into it, I notice that the `select` call in `kazoo.protocol.connection.ConnectionHandler._connect_attempt` experiences a `select.error` with an `errno` of `EINTR` -- which makes sense. Unfortunately, there's nothing in the call path that will handle it.

In this case the most appropriate thing (for `EINTR`) would be to simply retry the `select` call, but a quick and dirty solution would be to wrap the call with `self._socket_error_handling` which is what's used for the other two `select` calls in the class -- is that intentional?

---

I know that in this case the ephemeral znode indicating party membership will be cleaned up automatically when the session expires, but I'd rather not wait for the session to timeout, and this should probably be recoverable for processes which want to ignore `SIGINT`.

**Comment by bbangert** [comment]
Closing as I don't know if this still applies or what action should follow.
