### ISSUE TITLE
Should external dependencies be documented?

### ISSUE THREAD

**Issue by wangd** [python-zk/kazoo#197]
Some machines, e.g. HPC cluster nodes, may not have access to the public internet. Hence, to run kazoo on such machines, we would need to install all of its dependencies separately manually, because the normal install process (if the dependencies are not yet installed) fetches and installs them.

Can we (really, someone who knows it authoritatively) add this to the README or the readthedocs site? As far as I can tell, kazoo depends on gevent and greenlet python libs, but what else?

**Comment by hngrytgr** [comment]
requiring a system to have internet access to run the only supported installation method does not seem reasonable
