### ISSUE TITLE
KazooClient bug? connection time-out, but not retry another zk server.

### ISSUE THREAD

**Issue by catmonkeylee** [python-zk/kazoo#205]
My question is that: 
when client connect to yahoo.com:80, there is a timeout exception was throwed,  But it didn't retry connect to 127.0.0.1:2181( this is my real zk server).  Anybody can help me?  thanks.
# source code:

import logging
logging.basicConfig(level=logging.DEBUG)
from kazoo.client import KazooClient
from kazoo.retry import KazooRetry
_retry = KazooRetry(max_tries=1000, delay=0.5, backoff=2)
_zk = KazooClient(hosts="yahoo.com:80,127.0.0.1:2181", logger=logging, read_only=True, timeout=30, connection_retry=_retry)
_zk.start()
# _zk.stop()

log:

DEBUG:root:ZK loop started
DEBUG:root:Skipping state change
INFO:root:Connecting to yahoo.com:80
DEBUG:root:    Using session_id: None session_passwd: 00000000000000000000000000000000
INFO:root:Sending request(xid=None): Connect(protocol_version=0, last_zxid_seen=0, time_out=30000, session_id=0, passwd='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', read_only=True)
WARNING:root:Connection dropped: socket connection broken
DEBUG:root:Connection stopped
Traceback (most recent call last):
  File "/tmp/1.py", line 7, in <module>
    _zk.start()
  File "/home/s/apps/wdshopping/python/lib/python2.7/site-packages/kazoo-1.2.1-py2.7.egg/kazoo/client.py", line 476, in start
    raise self.handler.timeout_exception("Connection time-out")
# kazoo.handlers.threading.TimeoutError: Connection time-out

**Comment by genisd** [comment]
i'm facing this as well. did you ever figure it out?

**Comment by trobinsonpp** [comment]
Try setting the [kazoo.client.KazooClient.start timeout](http://kazoo.readthedocs.io/en/latest/api/client.html?highlight=client#kazoo.client.KazooClient.start) higher than the kazoo.client.KazooClient timeout.

For your example:
`_zk.start(timeout=40)`

**Comment by graysonchao** [comment]
^^^ Doing the above can help, but might mask an issue with timeouts once the connection is established. Kazoo seems to use the client session timeout (the one in kazoo.client.KazooClient) for each attempted TCP connection before negotiating a session, but later on, it divides this number by the number of hosts in the ensemble to decide on its internal "connect timeout" (e.g. how long to wait before a write request or a reconnect times out.)

So, if you set a low timeout in `kazoo.client.KazooClient.__init__`, you might run into issues where reconnecting or submitting requests times out much faster than you expected. If you set them equal or have the `__init__` timeout higher, then you can burn your entire `KazooClient.start` timeout on a single unresponsive host.

I'm opening a separate issue to check whether this is intended behavior.
