### ISSUE TITLE
DataWatch blocks forever if Zookeeper goes away

### ISSUE THREAD

**Issue by jimjh** [python-zk/kazoo#207]
Consider the following snippet

``` python
from kazoo.client import KazooClient

def w(*args, **kwargs):
    pass

client = KazooClient('localhost:2181')
client.start()

# kill zookeeper cluster

client.DataWatch('/', w) # <- blocks forever
```

I prefer to have `DataWatch` raise an exception when that happens.

Specifically, this behavior is caused by the following line in [`watchers.py`](https://github.com/python-zk/kazoo/blob/master/kazoo/recipe/watchers.py#L112)

``` python
self._retry = KazooRetry(max_tries=None, sleep_func=client.handler.sleep_func)
```

which retries infinitely.

A simple fix could be allowing a `retry` object to be passed into the `DataWatch` constructor as a parameter. This would allow the user to set a maximum number of retries, an interrupt function etc.

**Comment by bbangert** [comment]
Closing as I don't know if this still applies.
