### ISSUE TITLE
Expand RR DNS entries into list of available hosts

### ISSUE THREAD

**Issue by ltucker** [python-zk/kazoo#215]
For example if I have multiple DNS entries for "zk.example.com" set up:

10.0.0.10
10.0.0.11
10.0.0.12
10.0.0.13

kazoo.hosts.collect_hosts("zk.example.com") will return a single node "zk.example.com" while the java client will expand this into 4 nodes with the listed ip addresses.

During a call to client.start(), Kazoo will try the hostname "zk.example.com" once (on one of the addresses) and then give up (unless retries are configured).  If expanded, it would try each of these in a single try as if listed separately in the configuration.

Zookeeper FAQs mention this, not sure how expected/official it is:

http://wiki.apache.org/hadoop/ZooKeeper/FAQ#A8
"DNS round robin: this setup involves one hostname and a list of IPs. ZK clients correctly make used of a list of IPs returned by DNS query. Thus this setup works the same way as multiple hostname (IP) argument to zookeeper_init."

**Comment by toddpalino** [comment]
I just created PR #360 to expand the hostlist. It uses `socket.getaddrinfo` in collect_hosts to expand the list.

**Comment by bbangert** [comment]
PR merged as #372.
