### ISSUE TITLE
Add support for reconfig cluster membership operation

### ISSUE THREAD

**Issue by hannosch** [python-zk/kazoo#234]
ZK 3.5 introduced a new reconfig operation to change the cluster memberships at runtime. The feature was tracked in https://issues.apache.org/jira/browse/ZOOKEEPER-107. The bulk of the work happened in http://svn.apache.org/viewvc?view=revision&revision=1453693.

This is the new type code 16.

**Comment by rgs1** [comment]
WIP: https://github.com/rgs1/kazoo/tree/support-reconfig, comments welcomed! Will add tests later this week.

**Comment by rgs1** [comment]
So this PR has basic coverage for this feature: https://github.com/python-zk/kazoo/pull/333. That being said, there are some server-side bugs to be addressed (i.e.: https://issues.apache.org/jira/browse/ZOOKEEPER-2202), but it would be nice to have this in so I can support it in [zk-shell](https://github.com/rgs1/zk_shell)!

**Comment by jeffwidman** [comment]
It appears this was handled by #333
