### ISSUE TITLE
ACL on path

### ISSUE THREAD

**Issue by caderrik** [python-zk/kazoo#253]
Hi,

I'm trying to use ACL on a path but i've got an 'NoAuthError' exception that i don't understand. Please take a look at my code, what i've made wrong?

Tested with kazoo 2.0 on python 2.6.6

---- CODE ----
from kazoo.security import make_digest_acl
from kazoo.client import KazooClient

acl = make_digest_acl('hmon', 'test', read=True, write=True, create=True, delete=True, admin=True, all=True)

zk = KazooClient(hosts='localhost:2181', default_acl=[acl], auth_data=[list(acl.id)])
zk.start()

print "zk version:", zk.server_version()
print "connection auth:", zk.auth_data
print "create path:", zk.create("/hmon", b"5")
print "/hmon acls:", zk.get_acls("/hmon")
print "/hmon value:", zk.get("/hmon")
print "/hmon delete:", zk.delete("/hmon")

---- EXEC ----
zk version: (3, 4, 5)
connection auth: [['digest', u'hmon:S+dTa72qOgWzHyFwJA02dr8wyeA=']]
create path: /hmon
/hmon acls: ([ACL(perms=31, acl_list=['ALL'], id=Id(scheme=u'digest', id=u'hmon:S+dTa72qOgWzHyFwJA02dr8wyeA='))], ZnodeStat(czxid=47245404572, mzxid=47245404572, ctime=1414073477688, mtime=1414073477688, version=0, cversion=0, aversion=0, ephemeralOwner=0, dataLength=1, numChildren=0, pzxid=47245404572))
/hmon value:
Traceback (most recent call last):
  File "./test_zk.py", line 17, in <module>
    print "/hmon value:", zk.get("/hmon")
  File "/usr/lib/python2.6/site-packages/kazoo/client.py", line 978, in get
    return self.get_async(path, watch).get()
  File "/usr/lib/python2.6/site-packages/kazoo/handlers/threading.py", line 102, in get
    raise self._exception
kazoo.exceptions.NoAuthError: ((), {})

**Comment by StephenSorriaux** [comment]
I'm closing this since the answer as given. Thanks!
