### ISSUE TITLE
Unhandled Exception in Connection Loop: RuntimeError: ('xids do not match, expected %r received %r', 28, 27)

### ISSUE THREAD

**Issue by diranged** [python-zk/kazoo#254]
Two days ago we upgraded our servers from Kazoo 1.3.1 -> Kazoo 2.0. We started seeing a 10x increase in the number of connection failures ... and the recovery of those connections is far worse too. It looks like we're seeing a new exception being raised that we did not see before.

```
        "stack_trace": [
            "Traceback (most recent call last):", 
            "  File '/mnt/.venv/lib/python2.7/site-packages/kazoo/protocol/connection.py', line 531, in _connect_attempt", 
            "    response = self._read_socket(read_timeout)", 
            "  File '/mnt/.venv/lib/python2.7/site-packages/kazoo/protocol/connection.py', line 407, in _read_socket", 
            "    return self._read_response(header, buffer, offset)", 
            "  File '/mnt/.venv/lib/python2.7/site-packages/kazoo/protocol/connection.py', line 338, in _read_response", 
            "    'received %r', xid, header.xid)", 
            "RuntimeError: ('xids do not match, expected %r received %r', 28, 27)"
```

This is being caught by `kazoo.client` and throwing the `Unhandled exception in connection loop` error. I'm completely stumped, I can't seem to replicate this in my own dev environment... and it only happens sporadically in production.

**Comment by jeffwidman** [comment]
bump @diranged any updates per above?

Is it still reproducible?
