### ISSUE TITLE
Use of select.select() in threading handler is a problem

### ISSUE THREAD

**Issue by fried** [python-zk/kazoo#266]
I ran into a situation where an application (with a ton of open FDs) was calling my application in a popen and did not use close_fd. So the single fd passed into select.select in connection.py had a int value that was too large and select.select throws a ValueError. 

Using some other poller may be wise. 

Take a look at asyncio.selectors.DefaultSelector for a really nice solution to different poller support on different OS's

**Comment by harlowja** [comment]
Seems like your application should be fixed right (aka to close fds)?

**Comment by fried** [comment]
One doesn't always have control of how users call your application. 
But if I was actually using those fd's for other things then tried to open a kazoo client it would fail. Because the fd id number is too large for select.select, even though we only send one fd to select.
