### ISSUE TITLE
Periodically able to cause `server_version` to fail

### ISSUE THREAD

**Issue by harlowja** [python-zk/kazoo#274]
It appears like the following can be triggered (for unknown reasons) when calling into client.server_version()

```
File "/usr/lib/python2.7/dist-packages/kazoo/client.py", line 642, in server_version
string = ENVI_VERSION.match(data).group(1)
AttributeError: 'NoneType' object has no attribute 'group' 
```

This is happening periodically on kazoo 2.0 (periodically, and not all the time for rackspace who is seeing this intermittently); so this could be a zookeeper (happens on 3.4.5) bug or a kazoo one (or a mix of both).

**Comment by harlowja** [comment]
More data is being collected to see exactly what the server_version 'envi' command is returning.

**Comment by harlowja** [comment]
So talking with folks it seems this is known to be somewhat flakey due to the internals of zookeeper and the '4' letter word commands being known to not be very reliable:

https://issues.apache.org/jira/browse/ZOOKEEPER-1346 will hopefully make this better in the future.

**Comment by rgs1** [comment]
Yup. If you try:

```python
client.command('dump')
```
you'll see you get partial data some times too. That's because ZK closes the socket immediately after writing/flushing, which means you could still lose some.

**Comment by bbangert** [comment]
Should it maybe retry the operation and return None if there's an error?

**Comment by harlowja** [comment]
IMHO the hard part to determine is the 'error'; it could likely retry it, but what if it gets an environment like the following:

```
Environment:
zookeeper.version=3.<eom>
```

Or it could be truncated at:
```
Environment:
zookeeper.version=3.4.2
blah=blah
blah2=<eom>
```
The hard part is the first one (where the truncation happens right in the version number, the lack of a valid string can be easily retried, but a partial version string is the tough one, are they always 3 digits, if so, then it can likely be retried if its not 3 digits; otherwise its sorta hard to tell the difference between a partial version and one that isn't partial).

**Comment by harlowja** [comment]
This has been addressed (for now, until better zookeeper apis come out).
