### ISSUE TITLE
ConnectionLoss when using SequentialGeventHandler

### ISSUE THREAD

**Issue by wangxiangyu** [python-zk/kazoo#285]
hi, all
    when I use SequentialGeventHandler, a problem happened to me: "after the client is started , the connection is always closed after a period of time".
   My test code is as below:
<pre><code>
from kazoo.client import KazooClient
from kazoo.handlers.gevent import SequentialGeventHandler
import time
import logging
logging.basicConfig(level=logging.DEBUG)
zk=KazooClient(hosts='172.16.29.4:2181:2181', handler=SequentialGeventHandler())
zk.start()
zk.add_auth("digest", "wxy:all")
while True:
    time.sleep(30)
    print zk.get('/haha')
</code></pre>
And I get the error:
<pre><code>
INFO:kazoo.client:Connecting to 172.16.29.4:2181
DEBUG:kazoo.client:Sending request(xid=None): Connect(protocol_version=0, last_zxid_seen=0, time_out=10000, session_id=0, passwd='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', read_only=None)
INFO:kazoo.client:Zookeeper connection established, state: CONNECTED
DEBUG:kazoo.client:Sending request(xid=-4): Auth(auth_type=0, scheme='digest', auth='wxy:all')
DEBUG:kazoo.client:Sending request(xid=1): GetData(path='/haha', watcher=None)
WARNING:kazoo.client:Connection dropped: socket connection broken
WARNING:kazoo.client:Transition to CONNECTING
INFO:kazoo.client:Zookeeper connection lost
Traceback (most recent call last):
  File "test_gevent.py", line 11, in <module>
    print zk.get('/haha')
  File "/home/vagrant/.virtualenvs/zeus2/local/lib/python2.7/site-packages/kazoo-2.0-py2.7.egg/kazoo/client.py", line 978, in get
    return self.get_async(path, watch).get()
  File "/home/vagrant/.virtualenvs/zeus2/local/lib/python2.7/site-packages/gevent/event.py", line 242, in get
    raise self._exception
kazoo.exceptions.ConnectionLoss
</code></pre>

Any ideas? Thank you!

**Comment by ebourgeois** [comment]
Did you close this because you were able to resolve it? I am seeing the same thing with Kazoo 2.2.1 + gevent 1.1.1. Even if I put a KazooRetry, it never retries the connection and it stays in a SUSPENDED state.
