### ISSUE TITLE
Lock or RLock ?

### ISSUE THREAD

**Issue by sileht** [python-zk/kazoo#291]
Hi, 

I'm a bit confused about the kind of lock that kazoo implements, it's called Lock, but the documentation said it's a reentrant lock, but when I test it the release() don't look reentrant:

  lock.acquire() # return True
  lock.acquire() # return True
  lock.release() # release the lock
  lock.release() # should release the lock, but that have been already done by the previous call, code executed between both release() is no more protected by the lock...

Regards,

**Comment by harlowja** [comment]
Seems bad, lol.
