### ISSUE TITLE
SetPartitioner looses watches (my theory) if zookeeper goes down

### ISSUE THREAD

**Issue by Dinoshauer** [python-zk/kazoo#298]
Hello!

It seems that SetPartitioner looses it's watches if a zookeeper does down, so I have to restart the process and initialize a new connection to get it back to a normal state.

I've made an example that can reproduce the problem here, https://gist.github.com/Dinoshauer/2ac8d52980bb7476c107

To reproduce the weird state:
- start a quorum of zookeepers
- start 2 processes running `test-kazoo.py`
- kill one of the zookeepers that one of the processes connected to
- start a third `test-kazoo.py` process, you will see that the watcher is not being fired in one of them and the rest of the processes seems to have entered a dead-lock

**Comment by bbangert** [comment]
That is true, however, a recent pull request supposedly fixed this. Can you test the latest dev?

**Comment by Dinoshauer** [comment]
Sure. Just install off master I suppose?

**Comment by bbangert** [comment]
Yep, master would work.

**Comment by Dinoshauer** [comment]
Yep, it's working :)!
What's the forecast on a new release?

**Comment by radix** [comment]
I think this ticket can be closed because it's fixed, and a release has been made since the code was changed.

**Comment by StephenSorriaux** [comment]
Closing this issue since the has been fixed.
