### ISSUE TITLE
New tox based tests don't install gevent

### ISSUE THREAD

**Issue by hannosch** [python-zk/kazoo#328]
Since we switched to the tox test runner, we don't run any of the gevent tests anymore, since gevent isn't getting installed into the tox environment.

This used to work via:

`.travis.yml` sets an environment variable like `GEVENT_VERSION=0.13.8` (or 1.0.1).

The Makefile adds another check and figures out the Python version, and sets `GREENLET_SUPPORTED` accordingly. Inside the `make build` section, if greenlet is supported (not PyPy / not Python 3), the gevent dependencies get installed and finally gevent gets installed with a version restriction to GEVENT_VERSION.

But after the switch to tox, `make build` isn't used on travis anymore, but instead tox.ini is responsible for installing dependencies. This does install the gevent / eventlet dependenies, but not gevent of the specified version itself.

The tests `succeed` everywhere, since all the gevent based tests are skipped if it isn't available.

@harlowja any ideas here?

**Comment by harlowja** [comment]
Seems like we just need to have a few variations of gevent in tox.ini env(s) for 1.0.1 and 0.13.8 and then have those tested in travis, will get that fixed and up and running.
