### ISSUE TITLE
kazoo.recipe.queue.Queue get() block forever

### ISSUE THREAD

**Issue by vipjml** [python-zk/kazoo#352]
def _inner_get(self):
        if not self._children:
            self._children = self.client.retry(
                self.client.get_children, self.path)
            self._children = sorted(self._children)
        if not self._children:
            return None
        name = self._children[0]
        try:
            data, stat = self.client.get(self.path + "/" + name)
        except NoNodeError:  # pragma: nocover
            # the first node has vanished in the meantime, try to
            # get another one
            raise ForceRetryError()
        try:
            self.client.delete(self.path + "/" + name)
        except NoNodeError:  # pragma: nocover
            # we were able to get the data but someone else has removed
            # the node in the meantime. consider the item as processed
            # by the other process
            raise ForceRetryError()
        self._children.pop(0)
        return data

_inner_get should clear  self._children when NoNodeError raised  . if _children  is not clear,every time retry,_children   is the same,raise NoNodeError,case Queue.get() block forever.

**Comment by bbangert** [comment]
Closed by #359.
