### ISSUE TITLE
client can NOT call any operation when zookeeper server restart

### ISSUE THREAD

**Issue by elcricwu** [python-zk/kazoo#356]
when zookeeper server restarted and kazoo client have been reconnected，kazoo client can NOT call get_children operation. And there is no error information。when tracing this error, the code will stop in method: get in class "AsyncResult" of module "kazoo.handlers.utils and finally  it will stop at "self._condition.wait(timeout)". Is this a bug of kazoo!

**Comment by harlowja** [comment]
Anything is possible! Can u post code that can recreate the issue so that
it can be investigated, thx!

On Sunday, September 6, 2015, Circle <notifications@github.com> wrote:

> when zookeeper server restarted and kazoo client have been
> reconnected，kazoo client can NOT call get_children operation. And there is
> no error information。when tracing this error, the code will stop in method:
> get in class "AsyncResult" of module "kazoo.handlers.utils and finally it
> will stop at "self._condition.wait(timeout)". Is this a bug of kazoo!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-zk/kazoo/issues/356>.
>


-- 
--
facebook.com/jshharlow <http://www.facebook.com/jshharlow>
flickr.com/jshharlow
YIM: jshharlow

**Comment by elcricwu** [comment]
node_list = self.client.get_children(node_path, children_watcher)

**Comment by elcricwu** [comment]
Finally, we found that get_children CAN NOT be called in Kazoo's state listener. If you called any zk calls, it will block. Some detail is in this page:http://kazoo.readthedocs.org/en/latest/implementation.html#handlers。
```
This ensures that calls can be made to Zookeeper from any callback except for a state listener
 without worrying that critical session events will be blocked.
```

But I don't know why? Someone can explain that. Thanks.

**Comment by amazhar** [comment]
Hello elcricwu,
Are you now making get_children call in some handler? I'm having a similar problem when my client goes from SUSPENDED > CONNECTED > SESSION_EXPIRED > LOST > CONNECTION, call for publishing znode gets stuck. Have you found any solution/workaround other than implementing handlers? Thanks in advance!
Ali

def my_listener(self, state):
    if state == KazooState.LOST:
      logging.debug(" Kazoo state --> LOST")
	  // something
    elif state == KazooState.SUSPENDED:
      logging.debug(" Kazoo state --> SUSPENDED")
      // something   
    elif state == KazooState.CONNECTED:
      logging.debug(" Kazoo state --> CONNECTED")
      self.ownService['path'] = self.register_service(self.ownService['metadata'])  
      # create call in the above function gets stuck!!!

**Comment by elcricwu** [comment]
Hi amazhar,
You should NOT call any zk operations like get_children/get/delete in Kazoo's state listener directly. You should spawn a new thread to call zk operations. If you call zk operations directly in state listener, thread of state listener will be blocked.

**Comment by jeffwidman** [comment]
If I understand this issue thread correctly, this wasn't a bug, it was simply a misunderstanding of where/when to call code.
