### ISSUE TITLE
Timeouts in Travis CI tests

### ISSUE THREAD

**Issue by toddpalino** [python-zk/kazoo#361]
It appears there's some issue with the Travis CI tests that is causing tests to fail at random, mostly with timeout errors. I've been seeing this with PR #360 a lot, where I'm having to close and reopen the PR to get Travis CI tests to kick off again and hope they all come back clean. There doesn't appear to be any determinism as to what fails.

**Comment by harlowja** [comment]
Yup, travis appears to be flakey, shared CI environments have this problem in general :cry:

**Comment by bbangert** [comment]
These have been fixed mostly, I will rerun any that are experiencing it and will look at making it easier to restart a failed one.
