### ISSUE TITLE
ensure-zookeeper-env.sh not work any more

### ISSUE THREAD

**Issue by vipjml** [python-zk/kazoo#375]
zookeeper 3.4.6 is not on server any more. So any new submit can't past test.

https://travis-ci.org/python-zk/kazoo/jobs/97795666

I change it to 3.4.7,but still some test can't be passed:
https://travis-ci.org/python-zk/kazoo/builds/99687754

**Comment by harlowja** [comment]
Ok, this should be all fixed now. Thanks for reporting.
