### ISSUE TITLE
kazoo sdist tarball is missing docs/

### ISSUE THREAD

**Issue by apevec** [python-zk/kazoo#379]
At least in kazoo-2.2.1.tar.gz, also reproducible in fresh git checkout:

$ git clone git://github.com/python-zk/kazoo
$ cd kazoo
$ python ./setup.py sdist
$ tar ztvf dist/kazoo*tar.gz|grep docs
$

**Comment by harlowja** [comment]
Hmmm, that's no cool, where the docs go.

**Comment by apevec** [comment]
kazoo-2.0.zip is the last release on pypi which included docs but recreating sdist on 2.0 tag produces both zip or tar.gz without docs...

**Comment by harlowja** [comment]
Ya, its interesting since it seems like https://github.com/python-zk/kazoo/commits/master/MANIFEST.in has never included the docs dir.

**Comment by harlowja** [comment]
https://github.com/python-zk/kazoo/pull/380 might be all that is needed to fix this.

**Comment by apevec** [comment]
#380 fixes this, any plans for 2.2.2 new release?
