### ISSUE TITLE
Add support for SSL

### ISSUE THREAD

**Issue by 31z4** [python-zk/kazoo#382]
As SSL is [supported by Zookeeper starting from 3.5.1](https://issues.apache.org/jira/browse/ZOOKEEPER-2125) it would be nice to have it in kazoo.

**Comment by jeffwidman** [comment]
Pull requests welcome. 

Note that due to improvements in Python's SSL handling, it's probably easiest to only support SSL on Python >= 2.7.9 / 3.3:
https://docs.python.org/3/library/ssl.html
https://docs.python.org/2/library/ssl.html

**Comment by jeffwidman** [comment]
This is available in `master` now... many thanks to @StephenSorriaux for all his hard work in #513.

Please try it out, I would not be surprised if there are edgecases that get discovered.
