### ISSUE TITLE
KazooClient hosts list should accept a list of multiple endpoints

### ISSUE THREAD

**Issue by jeffwidman** [python-zk/kazoo#411]
Currently `KazooClient` accepts a list of multiple hosts as a single concatenated string: http://kazoo.readthedocs.io/en/latest/api/client.html#kazoo.client.KazooClient

It seems the API would be more pythonic if it also accepted the hosts as a native list:

```
['zk01:2181', 'zk02:2181', 'zk03:2181']
```

I can submit a PR for this, but only if I get confirmation the core team is open to this feature request.

See also https://github.com/DataDog/dd-agent/issues/2943#issuecomment-255780694 - for example, `KafkaClient` supports both the concatenated string and native list formats.

**Comment by harlowja** [comment]
Seems fair to me.

**Comment by eribeiro** [comment]
Hello folks,
I have just submitted a PR to address this issue (my first contribution to Kazoo). See if it fits your needs.

Best regards
