### ISSUE TITLE
Request for 2.3.0 release

### ISSUE THREAD

**Issue by toddpalino** [python-zk/kazoo#415]
Would it be possible to cut a new release from master (potentially 2.3.0)? There have been a lot of updates since the last release, which was 1.5 years ago, that are only in master. Many of us use released versions only and not being able to pick up these updates is problematic.

**Comment by norrs** [comment]
Would love a release to test this particular fix: https://github.com/python-zk/kazoo/pull/393

**Comment by toddpalino** [comment]
@harlowja, any possibility of this? Or are there blockers that can be worked on?

**Comment by harlowja** [comment]
Seems like it should be ok with me; though I do need to double check.

Any objections from @bbangert @hannosch  @rgs1 (or others)?

**Comment by bbangert** [comment]
Sounds fine to me.

**Comment by toddpalino** [comment]
Bump

**Comment by harlowja** [comment]
Beginning release.

**Comment by toddpalino** [comment]
Bump

**Comment by norrs** [comment]
Hm, I'm bumping this again.

Is there any other Contributors that are able to initiate the process of releasing this? 

If there is anything holding back the release then it would be nice to see issues references to this issue so maybe we can help out with killings bugs before you are confident with releasing.

Thanks.

**Comment by toddpalino** [comment]
@harlowja or @bbangert, can we please get a release cut for this?

**Comment by bbangert** [comment]
Sure, I'll cut a release on Tuesday (Monday is holiday here), and I'd prefer not to cut a release on Friday afternoon just in case any emergency bug releases are needed afterwards (it's been awhile since a release).

**Comment by bbangert** [comment]
Closing this as I'll be issuing the release shortly now that the PR's are cleaned up. Still reviewing and updating the changelog, should be out today or tomorrow!
