### ISSUE TITLE
Bytes response in python3

### ISSUE THREAD

**Issue by mluscon** [python-zk/kazoo#425]
Hi,

is it expected of get function to return a response in bytes instead of string in python3, or am I hitting some bug or misconfiguration?
`
>>> import kazoo.client
>>> c = kazoo.client.KazooClient('gaussalgo22:2181')
>>> c.start()
>>> c.get('/')
(b'response', ZnodeStat(czxid=0, mzxid=0, ctime=0, mtime=0, version=0, cversion=251109, aversion=0, ephemeralOwner=0, dataLength=0, numChildren=7, pzxid=21486453100))
`

Thank you for any suggestions.

**Comment by harlowja** [comment]
Prob should be bytes right?, I didn't think zookeeper stated that all values would be utf8 (or other encoding0?

**Comment by mluscon** [comment]
Ok, thank you for the explanation.
