### ISSUE TITLE
Update travis tests for min. version of 2.7/3.4

### ISSUE THREAD

**Issue by bbangert** [python-zk/kazoo#441]
2.6 is quite obsolete and some patches that add desired IPv6 support fail to work correctly on such an old Python. 3.3 is also generally out of use as well as most packages now require 3.4 or newer.

Tox should be updated to only test on 2.7 and 3.3 and above.

**Comment by jeffwidman** [comment]
Big fan of this, thank you! Makes our lives easier to develop `kazoo`.
