### ISSUE TITLE
Request to be added as maintainer?

### ISSUE THREAD

**Issue by jeffwidman** [python-zk/kazoo#444]
Would you be open to adding me as a maintainer? 

I wouldn't be super active, but I saw a number of PR's that were closed that I would be willing to handle updating/rebasing them, but only if I know there's a good chance they'll be merged (otherwise no sense spending the time on them). 

I'm also willing to help out on the issue tracker with issue triage.

Other projects that I help out in a similar fashion with include Flask, FactoryBoy, kafka-python, Jinja2, prezto, etc.

**Comment by bbangert** [comment]
Absolutely, I'll add you right now.

**Comment by jeffwidman** [comment]
Thanks!

**Comment by jeffwidman** [comment]
Hey @bbangert I finally got some time to help out, and started to go through the issue tracker, but it looks like my `collaborator` permissions have since been revoked?
