### ISSUE TITLE
Remove the use of variables named async or await

### ISSUE THREAD

**Issue by cooperlees** [python-zk/kazoo#455]
In Python 3.7 the use of `async` or `await` as variable names will cause errors as they are reserved keywords. Kazoo does this, we should get this fixed.

```
/data/users/cooper/binary#link-tree/kazoo/recipe/watchers.py:425: DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7
```
e.g.
https://github.com/python-zk/kazoo/blob/master/kazoo/recipe/watchers.py#L425-L427

**Comment by jeffwidman** [comment]
@cooperlees Care to submit a PR for this?

**Comment by cooperlees** [comment]
I've flagged this with our Zookeeper team. Hopefully someone there will. I strapped for time, just noticed this warning debugging a codebase that uses kazoo and thought I'd flag it.
