### ISSUE TITLE
Stop bundling virtualenv

### ISSUE THREAD

**Issue by jeffwidman** [python-zk/kazoo#462]
Is there a reason this project bundles `virtualenv`? 

https://github.com/python-zk/kazoo/tree/master/sw

It is referenced in the `Makefile`: https://github.com/python-zk/kazoo/blob/83b9f94e32594516a65cd90fcf4fc16a02156467/Makefile#L31

But I don't think it's needed anymore. For tests, `tox` handles all the venv's, and for development, modern python 3 already includes the `venv` module. 

Note to self: If removing this, also remove these references to the `sw` folder:
https://github.com/python-zk/kazoo/search?utf8=%E2%9C%93&q=sw&type=

cc @harlowja / @bbangert as I think you two are most likely to know history here

**Comment by hannosch** [comment]
I'm pretty sure (looking at the commit history) we used our own virtualenv copy to work around bugs in travis-ci (0cdb38186eeffe8306315f0ddf76dd003c753432). That's a 5+ year old bug which isn't around anymore.

I think it makes sense to instead rely on virtualenv being installed in the Python environment.

Inside the Makefile we could do something like:
```
GREENLET_SUPPORTED = yes
ifeq ($(findstring 3.,$(TRAVIS_PYTHON_VERSION)), 3.)
	GREENLET_SUPPORTED = no
	VENV_CMD = python -m venv .
else
	VENV_CMD = python -m virtualenv .
endif
ifeq ($(PYPY),yes)
	GREENLET_SUPPORTED = no
endif
```

And then later:
```
$(PYTHON):
	$(VENV_CMD)
```

That should keep the `make` / `make test` working under both Python 2 and 3.
