### ISSUE TITLE
Remove debian packaging files?

### ISSUE THREAD

**Issue by jeffwidman** [python-zk/kazoo#465]
Can we remove the Debian packaging files from this project?

In the worlds where I work/play, no one installs python libraries using debian packages. 

Instead they would do `apt-get install python-pip` followed by `pip install kazoo`. 

The one exception being system-focused libraries like `gevent` where there is a significant risk of stability issues with various flavors of Linux--there they _might_ install the OS-pre-packaged version to be sure it was tested with their OS.

Given all this, I wonder why we need to keep the Debian packaging around?
- I suspect the Debian packaging was added during a time when PyPI and `pip` were not quite so stable/ubiquitous workflow.
- Most of these files have not been updated in 5 years. Perhaps they don't need updating, but I suspect they do have some bitrot.
- I'm not sure how this might affect https://github.com/openstack/deb-kazoo, which appears to be an exact mirror of this project, despite the description for that repo saying that it's just the debian packaging for this project. I've never used OpenStack, perhaps they could simply bundle the Debian build scripts, without including `kazoo` itself. 
 - Removing the debian packaging files from `kazoo` itself might necessitate removing the `python-kazoo` package from the Debian project as well. This shouldn't cause any problems because of the aforementioned workflow of installing `pip` followed by `pip install kazoo`. I actually see removing this debian package from the debian projects as a good thing, because it frees up the maintainers to spend time on projects that do actually are better shipped as debian packages.

If the other maintainers are on board with this change, I am happy to handle putting together a PR and/or following up with other projects affected by this change.

**Comment by hannosch** [comment]
Maybe @spladug can comment on this. I think he requested those Debian files to be added initially.

**Comment by spladug** [comment]
I think it's fine to remove the files from this repository as they're maintained in Debian itself these days. Removing them won't mean having to remove it from Debian.

That said, Kazoo is a dependency of several other packages in Debian and is actively maintained there. I don't think it'd be helpful to try to get the library removed.

**Comment by hannosch** [comment]
Ok, sounds to me like the Debian files are unused and removing them from this repo shouldn't be a problem.

Since the python-kazoo package in Debian is maintained elsewhere, we don't have to change anything about it or make decisions here.
