### ISSUE TITLE
Update Continuous Integration to ZooKeeper 3.5.3-beta

### ISSUE THREAD

**Issue by tgockel** [python-zk/kazoo#477]
Currently, `.travis.yml` uses the to-be-released `ZOOKEEPER_VERSION=3.5.2-alpha`. The current release (as of 2017-08-24) of the 3.5 line is 3.5.3-beta. Unless there is some motivation to continue to test against the old ZK server, `.travis.yml` should be updated to use the newer version.

**Comment by jeffwidman** [comment]
Great idea!

Pull request welcome if you want to update it. Otherwise I'll try to do it in the next week or so.

**Comment by tgockel** [comment]
So this is somewhat annoying...it seems that the file fetched in `ensure-zookeeper-env` will be [`zookeeper-3.5.3-beta.tar.gz`](http://archive.apache.org/dist/zookeeper/zookeeper-3.5.3-beta/zookeeper-3.5.3-beta.tar.gz). Despite the `.tar.gz` file suffix, it is actually a non-gzipped tarball, which makes the `tar -zx` fail. Changing this to `tar -x` works, but of course breaks all the properly-compressed files. Aside from opening a bug against ZK's packaging, I'm not sure what to here.

**Comment by jeffwidman** [comment]
Ugh, that's no fun. 

Can you open a ticket on the Zookeeper Jira and link back to it here? 

Generally I've found that team is reasonably responsive, especially to something like this which sounds like a very annoying packaging bug that is likely to bite a lot of folks.

**Comment by tgockel** [comment]
Bug is [ZOOKEEPER-2885](https://issues.apache.org/jira/browse/ZOOKEEPER-2885). Hopefully I'll get an email when it's fixed.

**Comment by jeffwidman** [comment]
Perfect, as long as you're a watcher on the JIRA ticket you'll get an email...

**Comment by jeffwidman** [comment]
@tgockel now that this is fixed upstream, do you want to submit a PR containing your commit that fixes this?

**Comment by tgockel** [comment]
It's _marked_ as fixed, but the file hasn't propagated out to everywhere...there's some likelihood that it will not ever in a lot of mirrors, since people usually expect artifacts to be permanent.

**Comment by jeffwidman** [comment]
Is it still breaking on travis? That's really the point here, so if it's just their cache that needs updating I can file a bug there...

**Comment by tgockel** [comment]
Yeah...3.5.3 is beta anyway :-)
