### ISSUE TITLE
Adding recipe to conda-forge

### ISSUE THREAD

**Issue by mrocklin** [python-zk/kazoo#479]
I am adding a recipe for kazoo to [conda-forge](https://conda-forge.org/), a community-run build system for binary conda packages, [here](https://github.com/conda-forge/staged-recipes/pull/4090).

If there is someone who maintains this project that should be listed as maintainer, please let me know.  After this has been merged it will be possible to install kazoo through conda with the following command

    conda install -c conda-forge kazoo

**Comment by jeffwidman** [comment]
This is totally an aside, and just some context for you based on my personal experience at my day job. Please do not take this in any way as an official position of the `kazoo` team, despite my `collaborator` badge here.
---
I noticed you're doing this to ultimately support `pykafka`'s `BalancedConsumer`. 

My day job includes being the in-house Kafka resource at a python shop that is currently running production services that rely on `pykafka`'s `BalancedConsumer` as well as `kafka-python`'s `SimpleConsumer` and `KafkaConsumer`.

Based on that production experience, I would strongly encourage you to only use Kafka Consumer implementations that leverage Kafka's native group membership APIs and avoid any that rely on Zookeeper. I am in the middle of a 1.5 year project to migrate all our legacy consumers that use Zookeeper, and it is painful. So if you're starting new projects, you definitely want to start with the new style consumer groups. Currently, that means you should use either the `confluent-kafka-python`, `pykafka`'s `ManagedBalancedConsumer`, or `kafka-python`'s `KafkaConsumer`. 

Also, with the full caveat that I am a collaborator on the `kafka-python` project, I would be cautious about using `pykafka`...  it's a smooth API that feels very pythonic, but both https://github.com/Parsely/pykafka/issues/696#issuecomment-320790952 and https://github.com/Parsely/pykafka/issues/354#issuecomment-211508480 resulted in production emergencies for us. At the the time we hit those, I didn't know much about any of the python kafka libraries and was trying to decide which library to contribute to. However, when I looked at trying to fix those issues, they were non-trivial fixes that required reworking core pieces of the library. Plus encountering https://github.com/Parsely/pykafka/issues/697 while debugging wasn't exactly confidence inspiring. So personally I just decided it wasn't the library for me, at least given it's current design. That said, @emmet9001 is extremely responsive and easy to work with--I'm sure he's a great guy, and would quickly fix both issues if he had more time. 

Anyway, just some thoughts... I know the Kafka client library world for python is confusing, so this is what I wish someone had told me when I was asked to come up to speed on Kafka...

**Comment by StephenSorriaux** [comment]
Hi,

Thanks for the information. I guess you can add @python-zk/maintainers as maintainers.
