### ISSUE TITLE
Deprecation Warning [pass a configured retry object]

### ISSUE THREAD

**Issue by aliartiza75** [python-zk/kazoo#504]
Hello everyone,

I am trying to connect to a zookeeper node(code given below):  
```
zk_client = KazooClient(hosts=zk_addr, connection_retry=3, retry_delay=5)
```
But always got the following warning:
```
DeprecationWarning: Passing retry configuration param retry_delay to the client directly is deprecated, please pass a configured retry object (using param delay)
```
It says : 
```
please pass a configured retry object (using param delay)
```

I don't understand warning message, need direction in this regards.

Thank you

**Comment by jeffwidman** [comment]
This looks like something Kazoo needs to be updated to handle... ie, a valid bug due to a deprecation.

What version of Zookeeper is this?

**Comment by aliartiza75** [comment]
My zookeeper version is 
3.4.10-XXXXXXX

**Comment by aliartiza75** [comment]
@jeffwidman waiting for your response.

**Comment by jeffwidman** [comment]
This looks like a valid issue. However, since it's only a deprecation, I would expect `kazoo` will continue to work. I don't have time right now to fix this, but I'm happy to review PR's if anyone else wants to tackle this.

**Comment by aliartiza75** [comment]
@jeffwidman i am interested in it kindly guide me

**Comment by jimbobhickville** [comment]
It's pretty clearly documented in the Kazoo docs. You need to use a KazooRetry object instead of passing in an int. To accomplish that with your example, this should work:

```
from kazoo.retry import KazooRetry

retry = KazooRetry(max_tries=3
                                 delay=5,
                                 backoff=1)

zk_client = KazooClient(hosts=zk_addr, connection_retry=retry)
```

**Comment by aliartiza75** [comment]
@jimbobhickville thank you
