### ISSUE TITLE
Random return ipv4, ipv6 ip.

### ISSUE THREAD

**Issue by knight76** [python-zk/kazoo#506]
My environment OS X(10.11.6), python 3.6, kazoo 2.4.

I used below code :

self.conn = KazooClient(hosts="localhost:2181")
event = self.conn.start_async()
event.wait(timeout=1000)
print(self.conn._connection._socket)

But, I met the random result, ipv4 or ipv6 address.

<socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 62573), raddr=('127.0.0.1', 2181)>
<socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 62580), raddr=('127.0.0.1', 2181)>
<socket.socket fd=19, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 62587), raddr=('127.0.0.1', 2181)>
<socket.socket fd=21, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 62594, 0, 0), raddr=('::1', 2181, 0, 0)>﻿

But, When I use KazooClient with given 127.0.0.1:2181 parameter, only result is "ipv4 ip address", that I want.

self.conn = KazooClient(hosts="127.0.0.1:2181")
self.conn = KazooClient()

I think it is awkward. Can you check it?

**Comment by StephenSorriaux** [comment]
Hi,

AFAICT this sounds more like a configuration problem on your host.
