### ISSUE TITLE
Deletion of zk nodes happen even when authentication is in place 

### ISSUE THREAD

**Issue by RajeshwariS** [python-zk/kazoo#516]
I have a code snippet that creates a zk node called testacl

`from kazoo.client import KazooClient`
`from kazoo.security import make_digest_acl_credential, make_acl`
`host = 'super'`
`iqn_id = '123'`

`cred = make_digest_acl_credential(host, iqn_id)`
`cred_tuple = ('digest', "{0}:{1}".format(host,iqn_id))`
`acl = make_acl("digest", cred, read=True, write=True, create=True, delete=True, admin=True, all=False)`

`aclList = [acl]`
`authList = [cred_tuple]`

`zk = KazooClient(hosts='127.0.0.1:2181', timeout=10.0, client_id=None, handler=None, default_acl=aclList, auth_data=authList)`
`zk.start()`
`zk.create('testacl', "testacl", aclList, False, False, True)`

Once created, I check the ACL.
[zk: localhost:2181(CONNECTED) 14] getAcl /testacl
'digest,'super:muDnfXVcVPiNEq80ou0GCQ7bF14=
: cdrwa

Here is another code that simply tries to delete the node: 

from kazoo.client import KazooClient
from kazoo.security import make_digest_acl_credential

`zk1 = KazooClient(hosts='127.0.0.1:2181')`
`zk1.start()`
`zk1.delete('testacl')`

There is no ACL used on this, and yet, it is able to delete the /testacl node. 

[zk: localhost:2181(CONNECTED) 15] getAcl /testacl
Node does not exist: /testacl

Would like to know if I have missed any configuration that has to be in place. Thank you.

**Comment by StephenSorriaux** [comment]
Hi,

It seems like the `zk1.delete('testacl')` should raise a `NoAuthError`. Which version of kazoo are you using? Is this the complete code you used?

**Comment by RajeshwariS** [comment]
@StephenSorriaux Yes, this is the complete code. It should have raised, but, if you setAcl on a znode using digest scheme via a client, you can delete it. After a bit of digging, found out that the ACL has to be set on the parent node /, to avoid this.
