### ISSUE TITLE
Plan for new release

### ISSUE THREAD

**Issue by VojtechBartos** [python-zk/kazoo#530]
Hi guys,
is there any plan for another version bump ?

We needs SASL DIGEST-MD5 support which has been added recently and i would rather to not install package from github ;)

Thanks!

**Comment by StephenSorriaux** [comment]
Hi,

I'm seeing with the team when we can release the new version, I will come back to you once I get more information.

**Comment by VojtechBartos** [comment]
Hi @StephenSorriaux,
just ping if there is any update and you have more info ;)

Thanks!

**Comment by StephenSorriaux** [comment]
Hi @VojtechBartos,

I am sorry, I don't have any news for new. I will ask again.

**Comment by StephenSorriaux** [comment]
Hi @VojtechBartos, the fresh new 2.6.0 release of Kazoo is now available on pypi.

I am now closing this issue.

**Comment by VojtechBartos** [comment]
Thanks @StephenSorriaux!
