### ISSUE TITLE
How can I create a znode with make its path by transaction?

### ISSUE THREAD

**Issue by Oldmoooon** [python-zk/kazoo#541]
I need use transaction to create some znode, but I find out it is impossible that I want to create its path at the same time.
this is a group of znode:
```json
{
  "/path1/to/node1":"value",
  "/path2/to/node2":"value2",
  ...others...
}
```
How can I create/update those value (atomic operation)

**Comment by StephenSorriaux** [comment]
Hi,

I am not sure of what you are trying to do. Don't the `create()` method of the `TransactionRequest` class meet your requirements?

**Comment by Oldmoooon** [comment]
> Hi,
> 
> I am not sure of what you are trying to do. Don't the `create()` method of the `TransactionRequest` class meet your requirements?

yes, Client.create() has an argument "makepath", but TransactionRequest.create() do not have.

**Comment by StephenSorriaux** [comment]
Currently it seems to me that this is not possible, you'll need to create the parent znode beforehand

**Comment by Oldmoooon** [comment]
> Currently it seems to me that this is not possible, you'll need to create the parent znode beforehand

but I don't know which znode exists and which is not, so it raised exceptions😭️

**Comment by StephenSorriaux** [comment]
I think you will need to check, before your transaction, which znodes exist and which don't and, in your transaction, add the creation of those that don't exist before the creation of the one you first wanted. I don't see any better way to solve this...

This kind of feature seems interesting, don't hesitate to submit a PR if you want to.

**Comment by Oldmoooon** [comment]
I had solved the problem (delete the znodes at first), thanks for your help.
you can closed this issue.

**Comment by StephenSorriaux** [comment]
Thans for your feedback, it would certainly help others.

Closing this issue now.
