### ISSUE TITLE
ChildrenWatch can not be collected by gc after be stopped?

### ISSUE THREAD

**Issue by kulallwang** [python-zk/kazoo#542]
When the registered function return 'False', the ChildrenWatch is stopped. But it does not remove session watcher from listener. It means ChildrenWatch can not be collected by gc. The result is that the ChildrenWatch will be always increase and cause memory leakage.

**Comment by StephenSorriaux** [comment]
Hi,

Thanks for your issue. You're right, it seem like it would be better to also remove session watcher from the listener when `func()` is returning `False`.
Feel free to submit any PR if you have some times, I would be more than happy to merge a fix.

**Comment by StephenSorriaux** [comment]
Hi,

Thanks for your PR. I will try to review it today. Don't bother closing / re-opening your PR to trigger the tests, I will take care of it.
