### ISSUE TITLE
Upgrade to Kazoo 2.6.0 breaks backward compatibility with KazooRetry

### ISSUE THREAD

**Issue by ceache** [python-zk/kazoo#544]
The removal of `max_jitter` from `KazooRetry` parameters in 60366d2c7910fc833991fad8e04bbe33817c0544 break upgrade from previous versions.

If this is expected, I think it should be documented.
Otherwise a simple deprecation warning and keeping the argument in an inactive form could also be done.

**Comment by StephenSorriaux** [comment]
Hi,

You're right we should have kept the argument while displaying a deprecation warning message... If you have some times to fix this, please feel free to submit a PR.

**Comment by jeffwidman** [comment]
@StephenSorriaux did you see my comment in https://github.com/python-zk/kazoo/pull/521#discussion_r220348402?

**Comment by StephenSorriaux** [comment]
@jeffwidman No, I did not... I might be missing something but isn't the deprecation about the `KazooClient` object?

**Comment by ceache** [comment]
We did not either.

We hit this because we were creating `KazooRetry` objects directly, not through the `KazooClient` constructor, which is *not* displaying any deprecation warnings.

Shouldn't the this machinery be moved to `kazoo.retry` instead and consolidated?

**Comment by StephenSorriaux** [comment]
I'm closing this issue since #545 fixes it.
