### ISSUE TITLE
Why return tuple ? 

### ISSUE THREAD

**Issue by eromoe** [python-zk/kazoo#551]
### set 
```
zk.set(ZK_PATH, json.dumps(config).encode('utf-8'))
```

### get
```
config = zk.get(ZK_PATH)
config = config[0]
```
Since `zk.set` does't allow  `*args` ,  `zk.get` should not return tuple.

**Comment by StephenSorriaux** [comment]
Hi,

I'm not sure to understand where the issue is. `zk.get()` is returning a tuple with the value and the associated ZnodeStat object. Are you suggesting only the value should be returned?

**Comment by eromoe** [comment]
Yes.
I think `zk.get` should return value exact same as `zk.set`

**Comment by abhilash1in** [comment]
@eromoe why do you think so? What issues are you facing? What are you trying to do? Adding additional context makes it easier for others to understand your use case, suggest solutions and consider your request for change.

**Comment by eromoe** [comment]
@abhilash1in For consistency,  like  redis.set / redis.get . Because for me , zk is just a kv store .
