### ISSUE TITLE
Adding Python 3.7 support

### ISSUE THREAD

**Issue by mwysokin** [python-zk/kazoo#552]
Is there any work going on in order to allow using kazoo with Python 3.7?

**Comment by StephenSorriaux** [comment]
Hi,

There is not ay work going on but it seems to me that adding this would be easy. Feel free to submit a PR if you have some times on your side. If not, I will try to find a moment for this.

**Comment by jimbobhickville** [comment]
Just curious, what doesn't work with python 3.7 right now? I ask because we're using kazoo in a py37 project and seeing some weirdness with things like custom listeners never receiving `CONNECTED` events and some oddness around expired sessions. Wondering if that's related.

**Comment by ninowalker** [comment]
+1 - is there anything known to be broken or incompatible with 3.7? Python 3.7 is now almost one year old since the official release.

**Comment by dwo** [comment]
It looks like some work has been done already eg. https://github.com/python-zk/kazoo/commit/225d3369c7a0736125a9375951a079f70fbe9e79
