### ISSUE TITLE
Init client before fork, hangs called when after fork

### ISSUE THREAD

**Issue by ShireCiel** [python-zk/kazoo#554]
Problem  happened when using celery.
(I found py grpc cannot fork first, and i remove all init of grpc channel before celery forked. The celery still hangs).
And I debug step by step. I found when reuse Kazoo client after fork it was hangs.
So i removed all of Kazoo client init before my fork test, it was not hang and celery works well.
(But weird there is no problem in macos.)

**Comment by StephenSorriaux** [comment]
Hi,

Which version of python are you using? Also which version of Kazoo? Sounds like https://github.com/python-zk/kazoo/issues/536

**Comment by ShireCiel** [comment]
> Hi,
> 
> Which version of python are you using? Also which version of Kazoo? Sounds like #536

Python Version: 3.7.1
Kazoo Version : 2.5.0

**Comment by ShireCiel** [comment]
I upgraded Kazoo version to 2.6.1 It's not hangs after fork.
Thanks.

**Comment by StephenSorriaux** [comment]
Can you please provide a snippet so that I can do some testing on my side?

**Comment by ShireCiel** [comment]
I write a simple code for this.
`import os
import time
import kazoo
import logging
logging.basicConfig()
from kazoo.client import KazooClient

zk = KazooClient(hosts='127.0.0.1:2181')
zk.start()

pid = os.fork()
if pid != 0:
    print('I am Father, Child = {0}'.format(pid))
    time.sleep(1)
    print('Father Get:' + str(zk.get_children('/')))
    time.sleep(10)
    print('Fathe done!')

print('Child trying')
print('Child_GET' + str(zk.get_children('/')))
print('Child done')`
Child hangs when father still alive.

**Comment by StephenSorriaux** [comment]
You can't share a KazooClient between processes.

More infos https://github.com/python-zk/kazoo/issues/143#issuecomment-28134929

**Comment by ShireCiel** [comment]
> You can't share a KazooClient between processes.
> 
> More infos [#143 (comment)](https://github.com/python-zk/kazoo/issues/143#issuecomment-28134929)

Ok. Got it.
But it's really confusing that just hangs and no warning or error.
