### ISSUE TITLE
Can kazoo determine whether the current connected zkserver is a leader?

### ISSUE THREAD

**Issue by ChenJhua** [python-zk/kazoo#560]
Now, I have a problem that I need to find the leader of the zkserver cluster, but I have looked at the kazoo code, and it seems that there is no similar interface

**Comment by StephenSorriaux** [comment]
Hi,

You can use the `command()` [method](https://github.com/python-zk/kazoo/blob/master/kazoo/client.py#L701) from the `KazooClient` object and check if `Mode` equals to `leader` when sending `stat`

**Comment by ChenJhua** [comment]
Yeah, thank you
