### ISSUE TITLE
Datawatch duplicates data if creating by watchchildren loop

### ISSUE THREAD

**Issue by tanuj83** [python-zk/kazoo#561]
I want to monitor children and data under those children, as children are varying and can be deleted or added  to path.

```
zk = KazooClient(hosts=zookeeper,read_only=True,timeout=10)
zk.add_listener(my_listener)
zk.start()

    @zk.ChildrenWatch(path)
    def watch_children(children):
        children = [x.encode('UTF8') for x in children]
        print children
        for id in children:
            @zk.DataWatch(path +"/"+ id)
            def watch_brokers(data,stat,event=''):
               ----- code based on event -----


while True:
    time.sleep(1)
zk.stop()
```

The first time code works well and if any children gets deleted or added it provides proper result but when next time the children gets deleted and  added back, I get duplicate result from datawatch and it seems that previous datawatch was already running and loop created a duplicated datawatch.  how can I avoid this?   my children are not fixed value and those would be added/deleted anytime

**Comment by StephenSorriaux** [comment]
Hi,

Maybe @bbangert can provide some insights?

**Comment by tanuj83** [comment]
hi @StephenSorriaux 

looks like I found the issue, it creates single  data watch path only and no matter how many times datawatch was called but every time  it creates new object reference for same datawatch path and on changes of data, all referenced objects sends results back

**Comment by tanuj83** [comment]
I have fixed it by calling datawatch only once.

**Comment by tanuj83** [comment]
Thanks
