### ISSUE TITLE
async callback does not work

### ISSUE THREAD

**Issue by dubingchao** [python-zk/kazoo#564]
hi i am using gevent with kazoo, i am doing exactly as the async example ,but get nothing,the callback does not work,even not simply print any word,such as 123,please help!
code as below:

import sys

from kazoo.exceptions import ConnectionLossException
from kazoo.exceptions import NoAuthException

def my_callback(async_obj):
    try:
        children = async_obj.get()
        print 123
    except (ConnectionLossException, NoAuthException):
        sys.exit(1)

async_obj = zk.get_children_async("/some/node")
async_obj.rawlink(my_callback)

**Comment by dubingchao** [comment]
solved by attemping to downgrade gevent to 1.2.0. may be the latest version of gevent not fitted well.

**Comment by StephenSorriaux** [comment]
Thanks for your feedback.
