### ISSUE TITLE
conda-forge artifact for 2.6.0

### ISSUE THREAD

**Issue by mcguipat** [python-zk/kazoo#572]
There is currently no artifact published to [conda-forge](https://anaconda.org/conda-forge/kazoo) for the 2.6.0 release.  Is it possible for this to be added?

**Comment by StephenSorriaux** [comment]
Hi,

Thank you for the issue.

Yes, I am seeing how I can get the release published.

**Comment by StephenSorriaux** [comment]
Thanks to https://github.com/conda-forge/kazoo-feedstock/pull/5 the latest version (2.6.1) is now available on conda-forge.
