### ISSUE TITLE
After the network was disconnected, Kazoo was suspended

### ISSUE THREAD

**Issue by zio-pzl** [python-zk/kazoo#592]
Hi，
After network disconnection, kazoo was suspended and zookeeper configuration information was no longer updated.Many people have found this bug.This problem has been discovered and fixed on github: https://github.com/python-zk/kazoo/pull/579. But you have not released the new version of the package. So I hope you can update the package as soon as possible.Thank you.

**Comment by xffaxbb** [comment]
> Hi，
> After network disconnection, kazoo was suspended and zookeeper configuration information was no longer updated.Many people have found this bug.This problem has been discovered and fixed on github.The link is [https://github.com/python-zk/kazoo/pull/579/files](url). But you have not released the new version of the package. So I hope you can update the package as soon as possible.Thank you.

I have found this bug too. Please,  update the package as fast as possilble. Thank you.

**Comment by StephenSorriaux** [comment]
Hi,

We are planning to cut a new release very soon.

**Comment by StephenSorriaux** [comment]
2.7.0 is now live.
