### ISSUE TITLE
User-defined authentication class cannot retry after the session expires and reconnects

### ISSUE THREAD

**Issue by QuantumEnergyE** [python-zk/kazoo#602]
Because the scheme name of the custom authentication class is not digest, retry will not be triggered when the session expires and reconnects.

https://github.com/python-zk/kazoo/blob/34cdd60f26ff790618244450fd648b77f9f1353c/kazoo/protocol/connection.py#L726

**Comment by ceache** [comment]
I believe this issue was already resolved in the 2.7.0 release.
Can you please confirm you do not see this issue when using the latest kazoo?
