### ISSUE TITLE
recursive delete failed

### ISSUE THREAD

**Issue by Laurel-rao** [python-zk/kazoo#608]
![微信图片_20200508182314](https://user-images.githubusercontent.com/42195541/81397008-12198280-9159-11ea-9cbd-1fbdfff72ebc.jpg)
why i used the recursive, it still raise NotEmptyError

**Comment by ceache** [comment]
Hi,

Please provide the version of Kazoo you are using when you are encountering this issue.

Also, is the environment you are using "live" i.e. could other users, program or threads be modifying Zookeeper while you are running?

If so, it could be that someone created a child node in one of the path you are trying to delete. In a distributed system you have to handle these situations in your client code either by retrying or using some coordination (locks)

**Comment by Laurel-rao** [comment]
yes, i found the problem that i try to delete a node while other thread added a new child node.
But zookeeper-cli has ‘rmr’, then why you guys didn't use `rmr` .

**Comment by ceache** [comment]
This is expected.

You are supposed to handle it.
Either use locks to ensure no other thread is using that node or handle the
exception and retry.
It is up to you to choose what best fits your use case.
