### ISSUE TITLE
Does kazoo 2.8.0+ support Python 3.6?

### ISSUE THREAD

**Issue by gopackgo90** [python-zk/kazoo#625]
The [release notes for 2.8.0](https://github.com/python-zk/kazoo/releases/tag/2.8.0) seem to indicate that Python 3.6 is no longer supported:

> __PYTHON SUPPORTED VERSIONS CHANGE__: Please note that Kazoo no longer tests
> on Python 2.7, Python 3.6. Tested versions are 3.7, 3.8 and PyPy.

but Python 3.6 is still listed in [setup.py for 2.8.0](https://github.com/python-zk/kazoo/blob/2.8.0/setup.py#L59).

Can the supported versions of Python be clarified?

**Comment by StephenSorriaux** [comment]
Hello,

Thank you for this issue. Good point, we missed that. We will update the `setup.py` file.
