### ISSUE TITLE
can't delete zknode,  kazoo version is 2.8.0

### ISSUE THREAD

**Issue by FutureNear** [python-zk/kazoo#634]
code:

zkClient.start()
print(zkClient.get_children("/"))
zkClient.delete(path="persi_not_seq", recursive=True)
print(zkClient.get_children("/"))
zkClient.stop()

result：
['persi_no_seq', 'zookeeper', 'hadoop-ha', 'kafka', 'hive_zookeeper_namespace_hive', 'hbase']
['persi_no_seq', 'zookeeper', 'hadoop-ha', 'kafka', 'hive_zookeeper_namespace_hive', 'hbase']
[Finished in 1.4s]

**Comment by StephenSorriaux** [comment]
Hello,

I think you have a typo in your code:
`zkClient.delete(path="persi_not_seq", recursive=True)`
should be `zkClient.delete(path="persi_no_seq", recursive=True)` (the `t` should not be there)

**Comment by FutureNear** [comment]
Hello,
 Thank you very much!
