### ISSUE TITLE
Does kazoo provide a "zoo_remove_watches" interface similar to zookeeper C API

### ISSUE THREAD

**Issue by youweisheng** [python-zk/kazoo#638]
## What would you like to be added

When monitoring a znode with datawatch, if the znode has not changed, how to destroy the monitoring of datawatch

## Why is this needed
Does kazoo provide a "zoo_remove_watches" interface similar to zookeeper C API

**Comment by StephenSorriaux** [comment]
Not yet, see https://github.com/python-zk/kazoo/issues/233
