### ISSUE TITLE
CI: from travis-ci.org to .com / Github Actions?

### ISSUE THREAD

**Issue by StephenSorriaux** [python-zk/kazoo#651]
## What would you like to be added

Migrate the CI from travis-ci.org to travis-ci.com or Github Actions since:

![image](https://user-images.githubusercontent.com/16797053/128025076-1d27782d-1b5c-442d-b87a-d1d2ac6293ff.png)

## Why is this needed
So that CI works again.

**Comment by jeffwidman** [comment]
Let's drop travis. Github Actions or Azure Pipelines or CircleCI all appear to be decent options although I haven't played with them a ton.
