### ISSUE TITLE
Remove usage of `six`

### ISSUE THREAD

**Issue by a-ungurianu** [python-zk/kazoo#677]
`six` and the things it provides are only needed for the transition from python2 to python3. As it seems that this library no longer supports python2, it'd be nice to remove the usage of this library.

Happy to help clean it up

**Comment by StephenSorriaux** [comment]
Hello,

I personally am always in the favor of removing stuff. Python2 is not our target anymore, so your idea makes perfect sense. @ceache what are your thoughts?

**Comment by jeffwidman** [comment]
+1 from me.

@a-ungurianu care to submit a PR?
