### ISSUE TITLE
Decide what to do about Codecov

### ISSUE THREAD

**Issue by jeffwidman** [python-zk/kazoo#701]
> > This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=python-zk)

> I wonder if this is why you see the codecov things, as it tries leverage the Github App.
> @ceache I don't have the rights to add the app. Do you know someone who does?
> _Originally posted by @a-ungurianu in https://github.com/python-zk/kazoo/issues/700#issuecomment-1407777392_

I think the first question is whether we should keep Codecov??

Happy to keep if it others find it valuable, but I personally don't find Codecov useful, as I tend to simply look at a PR source directly and decide if they've got reasonable test coverage or not.

From there, we can either completely remove it, or fixup the GitHub app install.

Input @StephenSorriaux @a-ungurianu @ceache @bbangert ?

**Comment by ceache** [comment]
I just added it.

Does it resolve the issue? @a-ungurianu

**Comment by jeffwidman** [comment]
@ceache that was fast 😀 

Do you find it useful though?

**Comment by StephenSorriaux** [comment]
Hello,

I tend to find it useful: I do just like you said, Jeff, but also use the generated covering stats to check if my "impression" about the PR isn't biased somehow (ie. I did not overlook the PR).

**Comment by jeffwidman** [comment]
Sounds good, let's keep it for now then.

I just saw they were acquired by Sentry, so they're in good hands, and also unlikely to go defunct/bankrupt (which was one of my previous concerns actually): https://sentry.io/about/press-releases/sentry-acquires-codecov/

Down the road if we do run into problems, we could always wire up something like https://hynek.me/articles/ditch-codecov-python/ ourselves, but I have no appetite for that unless forced to.
