### ISSUE TITLE
New kazoo release to include SSL fixes

### ISSUE THREAD

**Issue by davemcphee** [python-zk/kazoo#720]
## What would you like to be added

#706 , fixes various SSL methods  that where deprecated in python3.10. Yay! The PR was merged in Feb 2023, any chance of a new kazoo release that incorporates this PR?

## Why is this needed
While the warnings are merely annoying, we're running kazoo in a FIPS enabled environment, where any TLS / SSL issues (or warnings) become much more serious from an auditing perspective. We'd love to bump our kazoo dependencies to the next version to mitigate these admittedly corporate problems :)  Any plans / timelines for a new kazoo release?

**Comment by StephenSorriaux** [comment]
Hello,

Thank you for the issue.

I believe a new release would be cut soon, on my side I was waiting on https://github.com/python-zk/kazoo/pull/681 to land so that our Windows users can enjoy the lib in its latest version.
I am just curious: have you been able to try the current `master` branch?

**Comment by StephenSorriaux** [comment]
Hello,

Just wanted to give a heads up that the 2.10.0 release is here now.
