### ISSUE TITLE
Documentation of the ZooKeeper wire protocol?

### ISSUE THREAD

**Issue by madelson** [python-zk/kazoo#723]
Apologies for misusing the issue tracker to ask this question, but I am trying to find documentation of ZooKeeper's "wire protocol" (aka the expected behavior of a client library). 

Is there a spec that kazoo itself is based on in this regard? Thanks!

**Comment by StephenSorriaux** [comment]
Hello,

No worries! I think you probably already have found it, but the official Developer guide would be of help: https://zookeeper.apache.org/doc/current/zookeeperProgrammers.html + https://zookeeper.apache.org/doc/current/recipes.html
When I doubt or if the documentation does not help, I personally end up in the official C client (https://github.com/apache/zookeeper/tree/master/zookeeper-client) and some other of the modules (recipe, server, specifications).
I can't tell about the initial implementation though, so if any previous maintainer reading this at the moment want to step in, please feel free!
