### ISSUE TITLE
Connecting to read only zookeeper

### ISSUE THREAD

**Issue by FatemeMirzaeii** [python-zk/kazoo#739]
I'm trying to connect to a zookeeper cluster in read_only mode, but with read_only=True flag I got an Exception:
"Exception raised during deserialization of request: Connect()"
and then connection will dropped.
What is the problem?
## Specifications
  - Kazoo version: tested with 2.8.0 and 2.9.0
  - Zookeeper version: 3.9.1 and 3.7

**Comment by StephenSorriaux** [comment]
Hello,

There is not enough information for us to be of any help, please try to follow the issue template... Anyway, I would recommend checking your ZK configuration, I just remembered [some things](https://github.com/python-zk/kazoo/blob/master/kazoo/testing/harness.py#L74) might be needed for RO sessions.
